### ISSUE TITLE
The file is not a valid VSIX package

### ISSUE THREAD

**Issue by jerone** [madskristensen/ImageSprites#10]
### Installed product versions
- Visual Studio: Microsoft Visual Studio Professional 2017 15.5.6 (VisualStudio.15.Release/15.5.6+27130.2027)
- This extension: 1.4.54

### Description
I'm getting and error window when installing from the [CI Build on Open VSIX Gallery](http://vsixgallery.com/extension/cd92c0c6-2c32-49a3-83ca-0dc767c7d78e/). It says that this is not a valid VSIX package.

![2018-03-04 12_22_12-vsix installer](https://user-images.githubusercontent.com/55841/36944995-1ef327b6-1fa7-11e8-843f-25bdc15fc10b.png)

Installation log:
```
4-3-2018 12:22:19 - Microsoft VSIX Installer
4-3-2018 12:22:19 - -------------------------------------------
4-3-2018 12:22:19 - vsixinstaller.exe version:
4-3-2018 12:22:19 - 15.5.99+g87f89a485e
4-3-2018 12:22:19 - -------------------------------------------
4-3-2018 12:22:19 - Command line parameters:
4-3-2018 12:22:19 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\<user>\AppData\Local\Temp\Image Sprites v1.4.54-2.vsix
4-3-2018 12:22:19 - -------------------------------------------
4-3-2018 12:22:19 - Microsoft VSIX Installer
4-3-2018 12:22:19 - -------------------------------------------
4-3-2018 12:22:20 - Initializing Install...
4-3-2018 12:22:20 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionPackageException: The file is not a valid VSIX package.
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Other extensions install normally.

**Comment by madskristensen** [comment]
Fixed

**Comment by ZishanAnsari** [comment]
How did you fix it, can you pls. let me know the steps?

**Comment by madskristensen** [comment]
@ZishanAnsari it has to do with building a correct .vsix v3 and it didn't before the fix

**Comment by soufianejayden** [comment]
hello madskristensen i have the same issue Sir How did you fix it i don't inderstand what you mention bellow here buddy
